#!/bin/bash

#Ten program wykrywa i drukuje linie z najpopularniejszymi błędami

GREP="grep --color=always --line-number --initial-tab"

$GREP "patrz[[:alpha:]]* się" $1
$GREP "puki" $1
$GREP "na prawdę" $1

$GREP "nie możliwe" $1

$GREP "[\.\?]\"'" $1 						#Znak interpunkcyjny poza cudzysłowem